application: te18st
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /clean
  script: main.py
  login: admin
- url: /.*
  script: main.py
